/**
 * Affirmations shown as the dashboard greeting — sourced verbatim from the
 * project's affirmations.rtf (the user-provided list; do not invent new
 * entries here, edit that list instead and regenerate).
 */
export const AFFIRMATIONS: readonly string[] = [
  "I am ready to let go.",
  "I deserve to move on.",
  "I know I can overcome this.",
  "I am letting go of everything that holds me back.",
  "I let go of the darkness and embrace the light.",
  "Today, I am choosing peace.",
  "I am ready for fresh beginnings.",
  "I let go of what I cannot change.",
  "I am worthy of choosing what is right for me.",
  "I allow myself to let go.",
  "I am free.",
  "I choose freedom.",
  "Every breath I take leads me forward.",
  "I am moving ahead in my life.",
  "I leave the past in the past.",
  "My heart knows how to heal.",
  "My life is a blessing.",
  "I am grateful for every moment.",
  "I am light and free of burden.",
  "My life is a joyful experience.",
  "I am releasing everything I don't need in my life.",
  "Each new moment is a new chance.",
  "I make the choice to move forward in my life.",
  "I keep what I need, and leave what I don't.",
  "I am ready to live in the present moment.",
  "I deserve happiness.",
  "I learn from my past and walk forward with freedom.",
  "I trust in the journey of my life.",
  "My life is mine and I choose to live it well.",
  "I deserve to feel good.",
  "Happiness is my best friend.",
  "I trust myself to create the life I want.",
  "It is possible to let go.",
  "I realize that letting go is good for me.",
  "I release guilt for choosing what I deserve.",
  "My life is worth it.",
  "My happiness is worth it.",
  "I am worth it.",
  "I welcome peace into my life.",
  "It is okay to choose happiness.",
  "I decide what a good life is for me.",
  "I am a magnet for miracles.",
  "I know I can rely on myself.",
  "I have infinite strength.",
  "I know I can make it through.",
  "My validation is enough.",
  "It is okay if everyone doesn't understand me.",
  "I am enough.",
  "I let go of the need to please everyone.",
  "I let go of the need for people's approval.",
  "I let go of the memories that bring me down.",
  "I embrace the power of my mind.",
  "I accept that I have everything I need within myself.",
  "I realize that I am the only one responsible for my happiness.",
  "I live in the moment I am in.",
  "I am allowing myself to feel good.",
  "I am proud of my journey and how far I’ve come.",
  "I am filled with positive, loving energy.",
  "I am aligned with the highest frequency of love.",
  "My inner joy is infinite, limitless, and abundant.",
  "I concentrate my thoughts on ideas and beliefs that make me feel good.",
  "I am confident, happy, healthy, and powerful.",
  "I deserve everything I want in life.",
  "I love myself unconditionally.",
  "I am appreciating every blessing, no matter how small.",
  "I am grateful for my sense of gratitude.",
  "I am living my life with awareness and gratitude.",
  "I am finding gratitude and joy every day.",
  "I am capable of unconditional love.",
  "I am willing to be at peace with myself and everyone.",
  "I am my greatest well-wisher.",
  "I am kind to myself and others.",
  "I am surrounded by healing energy.",
  "I am happy to be alive.",
  "I am grateful for my body.",
  "I am a special person.",
  "My inner dialogue is filled with love.",
  "I am a sanctuary of self-love and acceptance.",
  "Every cell in my body is infused with love.",
  "My love for myself grows with each day.",
  "Love is the foundation of my existence.",
  "I am worthy of love and respect.",
  "I am confident in my abilities.",
  "I am worthy of self-care and self-love.",
  "I choose to focus on my strengths and celebrate them.",
  "I am deserving of happiness and joy every day.",
  "I am a beautiful person, both inside and out.",
  "I am resilient and capable of bouncing back from setbacks.",
  "I am worthy of investing time in my personal growth.",
  "I am a source of positivity and inspiration for others.",
  "I am valuable and irreplaceable.",
  "I am proud of the progress I've made on my journey.",
  "I am open to receiving abundance from all directions.",
  "I am a work in progress, and that's perfectly okay.",
  "I am deserving of inner peace and tranquility.",
  "I am worthy of experiencing deep and meaningful connections.",
  "I am confident in my ability to create a life I love.",
  "I am worthy of my own love and affection.",
  "I own my strengths confidently.",
  "I attract positive opportunities.",
  "I trust my instincts completely.",
  "I am a magnet for good things.",
  "I speak with conviction.",
  "I am confident in every step.",
];

/** Pick one at random (call on the SERVER so hydration stays stable). */
export function randomAffirmation(): string {
  return AFFIRMATIONS[Math.floor(Math.random() * AFFIRMATIONS.length)];
}
